### ISSUE TITLE
Excluded from Hacktober fest 2023

### ISSUE THREAD

**Issue by theYogeshArora** [ElDiablo13X/hacktoberfest_2023#15]

**Comment by ElDiablo13X** [comment]
Please do not post such irrelevant issues

**Comment by ElDiablo13X** [comment]
Alot of people who have contributed to this repo already have received confirmation of their PRs being accepted maybe its an issues on your end. And yes I am well aware that this repo is name hacktoberfest_2023 :) because it is meant for 2023 and a handful of people have had their PRs accepted for hacktoberfest 2023. 
Well considering that you were affected quite a lot by this you may put a pull request on the 2022 repo meanwhile if this repo
has actually been excluded then I shall shut it down.
Hope this was helpful.

**Comment by theYogeshArora** [comment]
Sure, it was helpful... I just wanted to help fellow Devs so they can know that this repo is now excluded

**Comment by AbelAditya** [comment]
Heyy I have checked it out, yes the repo has been excluded. thank you for informing me and being a vigilant member of the community. I have mentioned the same in the readme.

**Comment by ElDiablo13X** [comment]
Heyy I have checked it out and yes the repo has been excluded. Thank you for informing me and for being a vigilant member of the community. I have mentioned the same in the readme.
